version: "3.9"

services:

  db:
    image: postgis/postgis:15-3.3
    container_name: postgres-marinetraffic

    restart: always

    environment:
      POSTGRES_DB: marinetraffic
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d marinetraffic"]
      interval: 10s
      timeout: 5s
      retries: 10


  mage:
    build: ./mage
    container_name: mage-ai

    ports:
      - "6789:6789"

    volumes:
      - ./mage:/home/src

    depends_on:
      db:
        condition: service_healthy

    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: marinetraffic
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    command: mage start marinetraffic

  api:

    build: ./api

    container_name: fastapi-service

    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy

    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: marinetraffic
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin


  dashboard:

    build: ./dashboard

    container_name: streamlit-dashboard

    ports:
      - "8501:8501"

    depends_on:
      - api

volumes:

  postgres_data: